### ISSUE TITLE
Laravel 5.7 & UUID

### ISSUE THREAD

**Issue by danyal14** [EmadAdly/laravel-uuid#25]
I recently install Laravel 5.7 and followed all the steps given in readme.
When running db:seed to add user, throws following error. Upon debugging deeper, looks like UUID is not attached when saving instance of User.

#### Seeder
            $user = new \App\User();
		$user->name = 'Xyz;
		$user->email ='email@xyz.dk';
		$user->password = bcrypt('secret123456');
		$user->save();

#### User Model

namespace App;
        
        use Emadadly\LaravelUuid\Uuids;
        use Laravel\Passport\HasApiTokens;
        use Illuminate\Database\Eloquent\SoftDeletes;
        use Illuminate\Notifications\Notifiable;
        use Illuminate\Foundation\Auth\User as Authenticatable;
        
        /**
         * Class User
         *
         * @package App
         */
        class User extends Authenticatable
        {
          use Notifiable, HasApiTokens;
          use SoftDeletes;
          use Uuids;
        
            /**
             * The attributes that should be mutated to dates.
             *
             * @var array
             */
            protected $dates = ['deleted_at'];
        
            /**
             * The attributes that are mass assignable.
             *
             * @var array
             */
            protected $fillable = [
                'name', 'email', 'password', 'api_token'
            ];
        
            /**
             * The attributes that should be hidden for arrays.
             *
             * @var array
             */
            protected $hidden = [
                'password', 'remember_token', 'api_token'
            ];
        
            /**
             * Indicates if the IDs are auto-incrementing.
             *
             * @var bool
             */
            public $incrementing = false;
        }

#### Error

    Symfony\Component\Debug\Exception\FatalThrowableError  : Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /home/vagrant/projects/web/laravel-projects/contentz/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 612 and exactly 2 expected at /home/vagrant/projects/web/laravel-projects/contentz/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:557

**Comment by Reubo** [comment]
Same here

**Comment by danyal14** [comment]
@Reubo My issue was resolved. It was as cache I had to clear

    php artisan cache:clear 
    php artisan config:clear

try this.

**Comment by iSWORD** [comment]
Shouldn't this be closed now?

**Comment by vishal-px** [comment]
I cleared the cache, but still getting the issue.

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in
```

**Comment by justashton** [comment]
Yep I've got the same issue.

**Comment by kylewallace** [comment]
Can confirm that this issue still exists using PHP 7.2.11 & Laravel 5.8.10. Fix mentioned by @danyal14 did not seem to help. Any other thoughts as to how you may have resolved it @danyal14?

**Comment by EmadAdly** [comment]
check #12
